language: python
sudo: false
python:
  - '3.7'
  - '3.8'
  - '3.9'

before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov

install:
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- pytest

after_success:
- codecov
